// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating an explanation
 * outlining the reasons for the Truth Probability Score of a news article.
 *
 * - generateExplanation - An async function that generates the explanation.
 * - GenerateExplanationInput - The input type for the generateExplanation function.
 * - GenerateExplanationOutput - The output type for the generateExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateExplanationInputSchema = z.object({
  headline: z.string().describe('The headline of the news article.'),
  truthScore: z.number().describe('The calculated truth score of the article (0-1).'),
  verdict: z.string().describe('The AI verdict on the article (Likely True, Likely False, Unverified).'),
  redFlags: z.array(z.string()).describe('A list of suspicious patterns found in the article.'),
  sourceCredibility: z.number().describe('A score representing the credibility of the source (0-1).'),
  factCheck: z.string().describe('The result of fact-checking the article against trusted databases.'),
});
export type GenerateExplanationInput = z.infer<typeof GenerateExplanationInputSchema>;

const GenerateExplanationOutputSchema = z.object({
  explanation: z.string().describe('A detailed explanation of the truth score, suspicious patterns, source verification, and confidence level.'),
});
export type GenerateExplanationOutput = z.infer<typeof GenerateExplanationOutputSchema>;

export async function generateExplanation(input: GenerateExplanationInput): Promise<GenerateExplanationOutput> {
  return generateExplanationFlow(input);
}

const generateExplanationPrompt = ai.definePrompt({
  name: 'generateExplanationPrompt',
  input: {schema: GenerateExplanationInputSchema},
  output: {schema: GenerateExplanationOutputSchema},
  prompt: `You are an AI assistant that explains the truth score of a news article.

  Based on the following information, generate a concise and easy-to-understand explanation for why the article received its truth score.
  Highlight any suspicious patterns, the source verification status, and the overall confidence level.

  Headline: {{{headline}}}
  Truth Score: {{{truthScore}}}
  Verdict: {{{verdict}}}
  Suspicious Patterns: {{#each redFlags}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Source Credibility: {{{sourceCredibility}}}
  Fact Check Results: {{{factCheck}}}

  Explanation:`,
});

const generateExplanationFlow = ai.defineFlow(
  {
    name: 'generateExplanationFlow',
    inputSchema: GenerateExplanationInputSchema,
    outputSchema: GenerateExplanationOutputSchema,
  },
  async input => {
    const {output} = await generateExplanationPrompt(input);
    return output!;
  }
);
